[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "rterm"
version = "0.1.0"

[dependencies]
gtk = "^0.1.2"
relm = "^0.7.6"
relm-attributes = "^0.7.0"
relm-derive = "^0.7.0"
vte-rs = "^0.1.0"
